
plugins {
    id 'java'
    id 'application'
    id 'org.gretty' version '4.1.5'
    id 'pmd'
}

repositories {
    mavenCentral()
}

def jakartaVersion = '6.1.0'
def apacheCommonsVersion = '3.17.0'

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:5.8.1'

//    testImplementation libs.junit
//    implementation libs.guava
//    implementation fileTree(include: ['*.jar'], dir: 'lib')
    compileOnly group: 'jakarta.servlet',
            name: 'jakarta.servlet-api',
            version: jakartaVersion

    implementation group: 'org.apache.commons',
            name: 'commons-lang3',
            version: apacheCommonsVersion

    testImplementation group: 'junit',
            name: 'junit',
            version: '4.13.2'

    testImplementation group: 'org.hamcrest',
            name: 'hamcrest-library',
            version: '2.2'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    mainClass = 'java.HelloServlet'
}

gretty {
    contextPath = '/'
}

pmd{
    consoleOutput = true
    toolVersion = "7.5.0"
    ruleSets = ["/"]
}

