dbUrl=jdbc:postgresql://db.mkalmo.eu:5432/icd0019_jp
hsqlDBUrl=jdbc:hsqldb:mem:db1;sql.syntax_pgs=true
dbUser=icd0019_jp
#dbUser=4ead5b
jwt.signing.key=r6m4GNX6voKiPh5pfCaWkQoG8d1E756ioKiPh2pfCaWk59ioKiPh2h5pfCaWkQoG8d1E756io