
DROP TABLE IF EXISTS orderRows;
DROP TABLE IF EXISTS orders;
DROP SEQUENCE IF EXISTS seq1;
DROP SEQUENCE IF EXISTS seq2;

CREATE SEQUENCE seq1 AS INTEGER START WITH 1;
CREATE SEQUENCE seq2 AS INTEGER START WITH 1;

CREATE TABLE orders (
    id BIGINT NOT NULL PRIMARY KEY DEFAULT nextval('seq1'),
    orderNumber VARCHAR(255)
);

CREATE TABLE orderRows (
    id BIGINT NOT NULL PRIMARY KEY DEFAULT nextval('seq2'),
    itemName VARCHAR(255),
    price INT,
    quantity INT,
    orders_id BIGINT,
    FOREIGN KEY (orders_id)
        REFERENCES orders ON DELETE CASCADE
);

DROP TABLE IF EXISTS authorities;
DROP TABLE IF EXISTS users;
DROP SEQUENCE IF EXISTS seq3;
DROP SEQUENCE IF EXISTS seq4;

CREATE SEQUENCE seq3 AS INTEGER START WITH 1;
CREATE SEQUENCE seq4 AS INTEGER START WITH 1;

CREATE TABLE users (
    id BIGINT NOT NULL PRIMARY KEY DEFAULT nextval('seq3'),
    userName VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    enabled BOOLEAN NOT NULL,
    firstName VARCHAR(255) NOT NULL
);

CREATE TABLE authorities (
    id BIGINT NOT NULL PRIMARY KEY DEFAULT nextval('seq4'),
    user_id BIGINT NOT NULL,
    authorityName VARCHAR(50) NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users
        ON DELETE CASCADE
);