DROP TABLE IF EXISTS orders CASCADE;

DROP TABLE IF EXISTS orderRows CASCADE;

CREATE TABLE orders (
    id SERIAL PRIMARY KEY NOT NULL ,
    orderNumber VARCHAR(255) NOT NULL
);

CREATE TABLE orderRows (
    id SERIAL PRIMARY KEY NOT NULL ,
    itemName VARCHAR(255) NOT NULL ,
    quantity INTEGER NOT NULL,
    price FLOAT NOT NULL ,
    orderId INT NULL,
    CONSTRAINT orderId FOREIGN KEY (orderId) REFERENCES orders(id) ON DELETE CASCADE
);