
DROP TABLE IF EXISTS orderRows CASCADE ;
DROP TABLE IF EXISTS orders CASCADE ;

DROP SEQUENCE IF EXISTS seq1 CASCADE ;
DROP SEQUENCE IF EXISTS seq2 CASCADE ;

CREATE SEQUENCE seq1 AS BIGINT START WITH 1;
CREATE SEQUENCE seq2 AS BIGINT START WITH 1;

CREATE TABLE orders (
    id BIGINT NOT NULL PRIMARY KEY DEFAULT nextval('seq1'),
    orderNumber VARCHAR(255)
);

CREATE TABLE orderRows (
    id BIGINT NOT NULL PRIMARY KEY DEFAULT nextval('seq2'),
    itemName VARCHAR(255),
    price INT,
    quantity INT,
    orders_id BIGINT,
    FOREIGN KEY (orders_id)
        REFERENCES orders ON DELETE CASCADE
);

DROP TABLE IF EXISTS authorities CASCADE ;
DROP TABLE IF EXISTS users CASCADE ;

DROP SEQUENCE IF EXISTS seq3 CASCADE ;
DROP SEQUENCE IF EXISTS seq4 CASCADE ;

CREATE SEQUENCE seq3 AS BIGINT START WITH 1;
CREATE SEQUENCE seq4 AS BIGINT START WITH 1;

CREATE TABLE users (
    id BIGINT NOT NULL PRIMARY KEY DEFAULT nextval('seq3'),
    userName VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    enabled BOOLEAN NOT NULL,
    firstName VARCHAR(255) NOT NULL,
    testField VARCHAR(123)

);

CREATE TABLE authorities (
    id BIGINT NOT NULL PRIMARY KEY DEFAULT nextval('seq4'),
    user_id BIGINT NOT NULL,
    authorityName VARCHAR(50) NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users
        ON DELETE CASCADE
);